name: ALLINMenu
version: 1.0.2
main: ru.allin.menu.ALLINMenu
api-version: '1.21'
author: ALLINONLINE
commands:
  menu:
    description: Открыть игровое меню ALLINONLINE
    usage: /menu
  allinmenu:
    description: Администрирование игрового меню
    usage: /allinmenu
    aliases: [amenu]
permissions:
  allinmenu.use:
    default: true
  allinmenu.admin:
    default: op
